apiVersion : v1
kind: Service
metadata:
  name: backend-service
  namespace: ecommerce-dev
  labels:
    app: ecommerce-backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: ecommerce-backend
    component: api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: ecommerce-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ecommerce-backend
      component: api
