apiVersion : v1
kind: ConfigMap
metadata:
  name: ecommerce-config  
  namespace: ecommerce-dev
  labels:
    app: ecommerce
    environment: development
data: 
#DATABASE CONFIG
  DB_HOST: postgres-service
  DB_PORT: "5432"

  #REDIS CONFIG
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  #APPLICATION CONFIG
  APP_ENV: development
  DEBUG: "true"
  LOG_LEVEL: "debug"
---
apiVersion : v1
kind: ConfigMap
metadata:
  name: ecommerce-config  
  namespace: ecommerce-prod
  labels:
    app: ecommerce
    environment: production
data: 
#DATABASE CONFIG
  DB_HOST: postgres-service
  DB_PORT: "5432" 

  #REDIS CONFIG
  REDIS_HOST: redis-service   
  REDIS_PORT: "6379"

  #APPLICATION CONFIG
  APP_ENV: production
  DEBUG: "false"
  LOG_LEVEL: "info"
  