apiVersion : v1  
kind: Service
metadata:
  name: frontend-service
  namespace: ecommerce-dev
  labels:
    app: ecommerce-frontend
    component: ui 
spec:
  type: LoadBalancer
  selector: 
    app: ecommerce-frontend
    component: ui 
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
# Pod Disruption Budget

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: ecommerce-dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
      component: ui