apiVersion : v1 
kind: Service
metadata:
  name: postgres-service
  namespace: ecommerce-dev
  labels:
    app: ecommerce
    component: database
    version: "16"
spec:
  type: ClusterIP
  selector:
    app: postgres
    component: database
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP