apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ecommerce-dev
  labels:
    app: ecommerce
    component: cache
spec:
  type: ClusterIP
  selector:
    app: redis
    component: cache
  ports:
  - name: redis
    port: 6379  
    targetPort: 6379
    protocol: TCP 