apiVersion : v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-dev
type: Opaque
data:
  POSTGRES_USER: ZWNvbW1lcmNlX3VzZXI=
  # echo -n "secure_password_123" | base64
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzEyMw==
  # echo -n "ecommerce_db" | base64
  POSTGRES_DB: ZWNvbW1lcmNlX2Ri
  # echo -n "super-secret-key-change-in-production" | base64
  SECRET_KEY: c3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-prod
type: Opaque
data:
  # Production secrets - different values
  POSTGRES_USER: ZWNvbW1lcmNlX3VzZXI=
  POSTGRES_PASSWORD: cHJvZC1zZWN1cmUtcGFzc3dvcmQtNDU2
  POSTGRES_DB: ZWNvbW1lcmNlX3Byb2Q=
  SECRET_KEY: cHJvZC1zdXBlci1zZWN1cmUtc2VjcmV0LWtleS0xMjM=
